### ISSUE TITLE
Which site?

### ISSUE THREAD

**Issue by Steve-Cook** [capital-chaplains/capchaps.org#4]
Matthew - this page says that I am logged in as CorpChaps.Com but the title above says "capital-chaplains / capchaps.org.  Is there a problem here?

**Comment by matt-cook** [comment]
Your username is set to "CorpChapsCom". Please go to this page:
https://github.com/settings/admin and click "Change Username" and set it
something associated you with you as an individual ("steve-cook" or
something like that).

The confusion is caused by your username being the same as the title of one
of your projects.

**Comment by matt-cook** [comment]
looking good! when an issue is resolved you can click the "close" button at the bottom.
